import time
import threading
from collections import defaultdict
from typing import Dict, Any, Optional, NamedTuple, List
from kormic.models.identity import Identity
from kormic.models.pedigree import Pedigree
from kormic.pedigree.builder import create_birth_record, initialize_pedigree
from kormic.interfaces.keys import KeyCustody
from kormic.interfaces.storage import RecordStore
from kormic.utils.serialize import sha256_hex

# ==============================================================================
# EXTRA UTILITY: AgentManager wrapper to simplify agent creation and storage.
# Handles identity generation, birth record signing, and database commit.
# ==============================================================================

class AgentEnrollmentResult(NamedTuple):
    agent_code: str
    twin_shares: list

class AgentManager:
    """
    High-level manager to simplify agent creation, tracking, and persistence.
    """
    def __init__(self, key_custody: KeyCustody, record_store: RecordStore, default_epoch: int = 1, registry_reader=None):
        self.key_custody = key_custody
        self.record_store = record_store
        self.default_epoch = default_epoch
        self.registry_reader = registry_reader
        # Per-agent locks serialize the read-modify-write in add_event so concurrent
        # writers to the SAME agent can't lose events. Different agents proceed in
        # parallel, so throughput doesn't collapse to a single global lock. The guard
        # lock only protects creation of the per-agent locks themselves.
        self._agent_locks: Dict[str, threading.Lock] = defaultdict(threading.Lock)
        self._locks_guard = threading.Lock()

    def _lock_for(self, agent_code: str) -> threading.Lock:
        with self._locks_guard:
            return self._agent_locks[agent_code]

    def _verify_list_containment(self, requested: Optional[List[str]], parent: Optional[List[str]], field_name: str) -> None:
        if requested:
            if not parent:
                raise ValueError(f"Containment violation: requested {field_name} but parent has none.")
            for item in requested:
                if item not in parent:
                    raise ValueError(f"Containment violation: requested {field_name} '{item}' is outside parent envelope.")

    def _verify_containment(self, requested: Dict[str, Any], parent: Dict[str, Any]) -> None:
        for key, value in requested.items():
            if key not in parent:
                raise ValueError(f"Containment violation: requested key '{key}' not in parent envelope.")
            if isinstance(value, list):
                parent_list = parent[key]
                if not isinstance(parent_list, list):
                    raise ValueError(f"Containment violation: parent '{key}' is not a list.")
                for item in value:
                    if item not in parent_list:
                        raise ValueError(f"Containment violation: requested scope '{item}' in '{key}' is outside parent envelope.")
            elif isinstance(value, dict):
                self._verify_containment(value, parent[key])
            else:
                if value != parent[key]:
                    raise ValueError(f"Containment violation: requested '{value}' for '{key}' does not match parent.")

    def register_new_agent(
        self,
        agent_type: str,            # STU, UNI, CMP, BLD, or DPL
        entity_ref: str,            # Owner identifier, e.g. 'priya7f3a'
        instance_num: str,          # Instance string or release digest
        real_world_id: str,         # Raw ID/profile text (will be hashed internally)
        guardrails: Dict[str, Any], # Allowed permissions and policies
        agent_pub_key: str = "",    # Hex agent public key for FAST challenge
        derived_from: Optional[str] = None, # Parent BAIN if this is a deployment
        deployment_salt: Optional[str] = None, # Salt generated by sidecar
        artifact_signature: Optional[str] = None, # BAIN Squatting Control: Vendor's signature over release
        vendor_pub_key: Optional[str] = None, # BAIN Squatting Control: Vendor's public key
        artifact_digest: Optional[str] = None, # BAIN Squatting Control: Digest of the software artifact
        approval_assertion: Optional[Dict[str, Any]] = None, # Identity-bound approval assertion
        read_scopes: Optional[List[str]] = None, # What data this agent is allowed to read
        allowed_egress: Optional[List[str]] = None # What IPs/Domains this agent is allowed to contact
    ) -> AgentEnrollmentResult:
        """
        Creates, signs, initializes, and stores a new agent in the database.
        Returns the unique agent code string and twin shares.
        """
        if derived_from:
            # Finding C FIX: Normalize if user passed the AgentEnrollmentResult tuple directly
            derived_from = getattr(derived_from, "agent_code", derived_from)
            
            parent_dict = self.record_store.get(derived_from)
            if not parent_dict:
                raise ValueError(f"Parent BAIN '{derived_from}' not found in registry.")
            parent_pedigree = Pedigree.from_dict(parent_dict)
            self._verify_containment(guardrails, parent_pedigree.birth_record.guardrails)
            self._verify_list_containment(read_scopes, parent_pedigree.birth_record.read_scopes, "read_scopes")
            self._verify_list_containment(allowed_egress, parent_pedigree.birth_record.allowed_egress, "allowed_egress")
            
        if agent_type == "BLD":
            if not artifact_signature or not vendor_pub_key or not artifact_digest:
                raise ValueError("BAIN registration requires artifact binding (vendor_pub_key, artifact_signature, and artifact_digest).")
            
            if not self.registry_reader:
                raise ValueError("BAIN registration requires a RegistryReader to verify vendor enrollment.")
            enrolled_vendor = self.registry_reader.get_enrolled_vendor(entity_ref)
            if not enrolled_vendor or enrolled_vendor.get('public_key') != vendor_pub_key:
                raise ValueError("Vendor Squatting Attempt: Key does not match enrolled vendor or vendor not enrolled.")
            
            from kormic.crypto.algorithms import MLDSASigner
            payload = (entity_ref + instance_num + artifact_digest).encode('utf-8')
            try:
                sig_bytes = bytes.fromhex(artifact_signature)
                pub_bytes = bytes.fromhex(vendor_pub_key)
                from kormic.crypto.agility import require_allowed_algorithm
                vendor_alg = enrolled_vendor.get('sig_alg')
                require_allowed_algorithm(vendor_alg)
                if not MLDSASigner.verify(vendor_alg, pub_bytes, payload, sig_bytes):
                    raise ValueError("Artifact signature verification failed.")
            except Exception as e:
                raise ValueError(f"Invalid artifact binding: {str(e)}")

            if not approval_assertion:
                raise ValueError("BLD agents require a verified approval_assertion")

            from kormic.models.approval import DelegationAssertion
            from kormic.verify.approval import verify_delegation_assertion
            try:
                _assertion = DelegationAssertion.from_dict(approval_assertion)
                verify_delegation_assertion(_assertion, self.registry_reader, "release", artifact_digest, spend_nonce=True)
            except Exception as e:
                raise ValueError(f"Invalid approval assertion: {str(e)}")

        # 1. Calculate privacy hash for real-world identity
        realid_hash = sha256_hex(real_world_id)

        # 2. Build structured Identity
        identity = Identity(
            agent_type=agent_type,
            entity_ref=entity_ref,
            instance=instance_num,
            realid_ref=realid_hash
        )
        agent_code = identity.to_string()

        # 3. Save sidecar salt locally if provided
        if deployment_salt:
            self.record_store.put_salt(agent_code, deployment_salt)

        # 4. Create Birth Record (Signed by epoch key)
        birth = create_birth_record(
            identity=identity,
            guardrails=guardrails,
            epoch_number=self.default_epoch,
            sig_alg=getattr(self.key_custody, "sig_alg", "ML-DSA-87"),
            hash_alg=getattr(self.key_custody, "hash_alg", "SHA-256"),
            key_custody=self.key_custody,
            agent_pub_key=agent_pub_key,
            derived_from=derived_from,
            vendor_pub_key=vendor_pub_key,
            artifact_digest=artifact_digest,
            approval_assertion=approval_assertion,
            read_scopes=read_scopes,
            allowed_egress=allowed_egress
        )

        # 4. Initialize Pedigree (Creates head_0 summary)
        pedigree = initialize_pedigree(birth)

        # 5. Save the initialized pedigree into RecordStore database (SQLite)
        self.record_store.put(agent_code, pedigree.to_dict())
        
        # 6. Immediately seal the baseline Twin (0 events)
        from kormic.crypto.twin import TwinManager
        sealed_blob, shares = TwinManager.seal_twin(pedigree, self.key_custody)
        self.record_store.put_twin(agent_code, sealed_blob)

        return AgentEnrollmentResult(agent_code, shares)

    def add_event(self, agent_code: str, event_data: str, snapshot_k: int = 5) -> Optional[list]:
        """
        Adds a history event. Implements the High-Churn Snapshot Model (Section 6.4).
        Returns new Shamir shares if a Snapshot Twin was sealed on this event, else None.
        """
        import time
        from kormic.pedigree.builder import append_history_event
        from kormic.crypto.twin import TwinManager

        # The entire read-modify-write must be atomic per agent. Without this lock,
        # concurrent callers each read the same head, append, and write back, and the
        # last write wins — events vanish AND the surviving chain still verifies clean,
        # which is the worst failure mode for a tamper-evident log. verify_full cannot
        # detect a truncation that never entered the chain, so the guarantee has to be
        # enforced here at write time.
        with self._lock_for(agent_code):
            # 1. Fetch live pedigree
            ped_dict = self.record_store.get(agent_code)
            if not ped_dict:
                raise ValueError("Agent not found in live database.")

            pedigree = Pedigree.from_dict(ped_dict)

            # 2. Add Event
            pedigree = append_history_event(pedigree, event_data, time.time())
            seq = len(pedigree.history)

            # 3. Update live DB
            self.record_store.put(agent_code, pedigree.to_dict())

            # 4. Snapshot Twin Logic (High-Churn optimization)
            # We only encrypt and seal the full twin every K events to save bandwidth.
            # This means on restore, we accept a bounded data loss of up to K-1 events.
            if seq % snapshot_k == 0:
                sealed_blob, new_shares = TwinManager.seal_twin(pedigree, self.key_custody)
                self.record_store.put_twin(agent_code, sealed_blob)
                return new_shares

        return None
