# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import meshkor_pb2 as meshkor__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

# if _version_not_supported:
#     raise RuntimeError(
#         f'The grpc package installed is at version {GRPC_VERSION},'
#         + ' but the generated code in meshkor_pb2_grpc.py depends on'
#         + f' grpcio>={GRPC_GENERATED_VERSION}.'
#         + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
#         + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
#     )


class MeshKorSidecarStub:
    """The central service hosted by the Sidecar Daemon on localhost
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnrollAgent = channel.unary_unary(
                '/meshkor.v1.MeshKorSidecar/EnrollAgent',
                request_serializer=meshkor__pb2.EnrollRequest.SerializeToString,
                response_deserializer=meshkor__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.GetChallenge = channel.unary_unary(
                '/meshkor.v1.MeshKorSidecar/GetChallenge',
                request_serializer=meshkor__pb2.ChallengeRequest.SerializeToString,
                response_deserializer=meshkor__pb2.ChallengeResponse.FromString,
                _registered_method=True)
        self.GetPedigree = channel.unary_unary(
                '/meshkor.v1.MeshKorSidecar/GetPedigree',
                request_serializer=meshkor__pb2.PedigreeRequest.SerializeToString,
                response_deserializer=meshkor__pb2.PedigreeResponse.FromString,
                _registered_method=True)
        self.RecordEvent = channel.unary_unary(
                '/meshkor.v1.MeshKorSidecar/RecordEvent',
                request_serializer=meshkor__pb2.RecordRequest.SerializeToString,
                response_deserializer=meshkor__pb2.RecordResponse.FromString,
                _registered_method=True)
        self.VerifyToken = channel.unary_unary(
                '/meshkor.v1.MeshKorSidecar/VerifyToken',
                request_serializer=meshkor__pb2.VerifyRequest.SerializeToString,
                response_deserializer=meshkor__pb2.VerifyResponse.FromString,
                _registered_method=True)


class MeshKorSidecarServicer:
    """The central service hosted by the Sidecar Daemon on localhost
    """

    def EnrollAgent(self, request, context):
        """Enrolls a new agent pubkey and fetches its Birth Record
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChallenge(self, request, context):
        """Fetches a fresh challenge nonce for interactive token minting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPedigree(self, request, context):
        """Fetches the agent's pedigree (for syncing history)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordEvent(self, request, context):
        """Anchors an event using Hash-Only Privacy
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """Local verification of the token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshKorSidecarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnrollAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollAgent,
                    request_deserializer=meshkor__pb2.EnrollRequest.FromString,
                    response_serializer=meshkor__pb2.EnrollResponse.SerializeToString,
            ),
            'GetChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChallenge,
                    request_deserializer=meshkor__pb2.ChallengeRequest.FromString,
                    response_serializer=meshkor__pb2.ChallengeResponse.SerializeToString,
            ),
            'GetPedigree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPedigree,
                    request_deserializer=meshkor__pb2.PedigreeRequest.FromString,
                    response_serializer=meshkor__pb2.PedigreeResponse.SerializeToString,
            ),
            'RecordEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEvent,
                    request_deserializer=meshkor__pb2.RecordRequest.FromString,
                    response_serializer=meshkor__pb2.RecordResponse.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=meshkor__pb2.VerifyRequest.FromString,
                    response_serializer=meshkor__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshkor.v1.MeshKorSidecar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meshkor.v1.MeshKorSidecar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshKorSidecar:
    """The central service hosted by the Sidecar Daemon on localhost
    """

    @staticmethod
    def EnrollAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshkor.v1.MeshKorSidecar/EnrollAgent',
            meshkor__pb2.EnrollRequest.SerializeToString,
            meshkor__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshkor.v1.MeshKorSidecar/GetChallenge',
            meshkor__pb2.ChallengeRequest.SerializeToString,
            meshkor__pb2.ChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPedigree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshkor.v1.MeshKorSidecar/GetPedigree',
            meshkor__pb2.PedigreeRequest.SerializeToString,
            meshkor__pb2.PedigreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshkor.v1.MeshKorSidecar/RecordEvent',
            meshkor__pb2.RecordRequest.SerializeToString,
            meshkor__pb2.RecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshkor.v1.MeshKorSidecar/VerifyToken',
            meshkor__pb2.VerifyRequest.SerializeToString,
            meshkor__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
