# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshkor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# _runtime_version.ValidateProtobufRuntimeVersion(
#     _runtime_version.Domain.PUBLIC,
#     7,
#     35,
#     1,
#     '',
#     'meshkor.proto'
# )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmeshkor.proto\x12\nmeshkor.v1\"\x8e\x01\n\rEnrollRequest\x12\x12\n\nagent_type\x18\x01 \x01(\t\x12\x12\n\nentity_ref\x18\x02 \x01(\t\x12\x10\n\x08instance\x18\x03 \x01(\t\x12\x15\n\rreal_world_id\x18\x04 \x01(\t\x12\x15\n\rmanifest_json\x18\x05 \x01(\t\x12\x15\n\ragent_pub_key\x18\x06 \x01(\t\"\x1d\n\x0e\x45nrollResponse\x12\x0b\n\x03\x61in\x18\x01 \x01(\t\"\x1e\n\x0fPedigreeRequest\x12\x0b\n\x03\x61in\x18\x01 \x01(\t\")\n\x10PedigreeResponse\x12\x15\n\rpedigree_json\x18\x01 \x01(\t\"\x12\n\x10\x43hallengeRequest\"\"\n\x11\x43hallengeResponse\x12\r\n\x05nonce\x18\x01 \x01(\t\"0\n\rRecordRequest\x12\x0b\n\x03\x61in\x18\x01 \x01(\t\x12\x12\n\nevent_data\x18\x02 \x01(\t\"\"\n\x0eRecordResponse\x12\x10\n\x08new_head\x18\x01 \x01(\t\"0\n\rVerifyRequest\x12\x0b\n\x03\x61in\x18\x01 \x01(\t\x12\x12\n\ntoken_json\x18\x02 \x01(\t\"0\n\x0eVerifyResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t2\xf9\x02\n\x0eMeshKorSidecar\x12\x44\n\x0b\x45nrollAgent\x12\x19.meshkor.v1.EnrollRequest\x1a\x1a.meshkor.v1.EnrollResponse\x12K\n\x0cGetChallenge\x12\x1c.meshkor.v1.ChallengeRequest\x1a\x1d.meshkor.v1.ChallengeResponse\x12H\n\x0bGetPedigree\x12\x1b.meshkor.v1.PedigreeRequest\x1a\x1c.meshkor.v1.PedigreeResponse\x12\x44\n\x0bRecordEvent\x12\x19.meshkor.v1.RecordRequest\x1a\x1a.meshkor.v1.RecordResponse\x12\x44\n\x0bVerifyToken\x12\x19.meshkor.v1.VerifyRequest\x1a\x1a.meshkor.v1.VerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshkor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENROLLREQUEST']._serialized_start=30
  _globals['_ENROLLREQUEST']._serialized_end=172
  _globals['_ENROLLRESPONSE']._serialized_start=174
  _globals['_ENROLLRESPONSE']._serialized_end=203
  _globals['_PEDIGREEREQUEST']._serialized_start=205
  _globals['_PEDIGREEREQUEST']._serialized_end=235
  _globals['_PEDIGREERESPONSE']._serialized_start=237
  _globals['_PEDIGREERESPONSE']._serialized_end=278
  _globals['_CHALLENGEREQUEST']._serialized_start=280
  _globals['_CHALLENGEREQUEST']._serialized_end=298
  _globals['_CHALLENGERESPONSE']._serialized_start=300
  _globals['_CHALLENGERESPONSE']._serialized_end=334
  _globals['_RECORDREQUEST']._serialized_start=336
  _globals['_RECORDREQUEST']._serialized_end=384
  _globals['_RECORDRESPONSE']._serialized_start=386
  _globals['_RECORDRESPONSE']._serialized_end=420
  _globals['_VERIFYREQUEST']._serialized_start=422
  _globals['_VERIFYREQUEST']._serialized_end=470
  _globals['_VERIFYRESPONSE']._serialized_start=472
  _globals['_VERIFYRESPONSE']._serialized_end=520
  _globals['_MESHKORSIDECAR']._serialized_start=523
  _globals['_MESHKORSIDECAR']._serialized_end=900
# @@protoc_insertion_point(module_scope)
